data:
  raw: data/raw
  processed: data/processed
  binary_masks: data/processed/binary_masks
  binary_masks_patches: data/processed/binary_masks_patches
  raw_images_patches: data/processed/raw_images_patches
  train_images: data/train/train_images/train
  train_masks: data/train/train_masks/train
  val_images: data/val/val_images/val
  val_masks: data/val/val_masks/val
models: models
tensorboard_logs: tb_logs
config_path: config/config.yaml   
hyperparams_path: config/hyperparameters.yaml  